name: scribble
description: Connect through art, without leaving your homescreen.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Geologica-Regular
      fonts:
        - asset: assets/fonts/Geologica/static/Geologica-Regular.ttf
          weight: 400
    - family: Geologica-Medium
      fonts:
        - asset: assets/fonts/Geologica/static/Geologica-Medium.ttf
          weight: 500
    - family: Geologica-Bold
      fonts:
        - asset: assets/fonts/Geologica/static/Geologica-Bold.ttf
          weight: 600
