name: scribble
description: Connect with loved ones through art, without leaving your homescreen.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_dial_code: ^1.2.0
  flutter_multi_formatter: ^2.11.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.9.1
  get_it: ^7.6.0
  get: ^4.6.5
  timer_count_down: ^2.2.2
  firebase_database: ^10.2.3
  camera: ^0.10.5+2
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  auto_size_text: ^3.0.0
  image: ^4.0.17
  flutter_drawing_board: ^0.4.4+2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Geologica-Regular
      fonts:
        - asset: assets/fonts/Geologica/static/Geologica-Regular.ttf
          weight: 400
    - family: Geologica-Medium
      fonts:
        - asset: assets/fonts/Geologica/static/Geologica-Medium.ttf
          weight: 500
    - family: Geologica-Bold
      fonts:
        - asset: assets/fonts/Geologica/static/Geologica-Bold.ttf
          weight: 600
